from snakemake.utils import min_version

#### set minimum snakemake version #####
min_version("6.15.5")


##### setup report #####
configfile: "config/config.yaml"


##### load rules #####
include: "rules/common.smk"
include: "rules/filtering.smk"
include: "rules/plasmid_reconstruction.smk"


##### target rules #####
rule all:
    input:
        expand(
            "results/{isolate}.genome.fa",
            "results/{isolate}.plasmids.fa",
            isolate=samples["isolate"],
        ),
